[package]
name = "compression_tool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = 'src/mod.rs'

[dependencies]
itertools = "^0.13.0"

[dev-dependencies]
console = "0.15.8"
indicatif = "0.17.8"
prettytable-rs = "0.10.0"
unbytify = "0.2.0"

[profile.release]
opt-level = "s"

[profile.dev]
opt-level = 3
